In [1]:
1

1

In [2]:
1.00

1.0

In [3]:
1+1.0

2.0

In [4]:
2**4

16

In [5]:
  2**8

256

In [6]:
4%3

1

In [7]:
5^3

6

In [8]:
count =8
print(count)

8


In [9]:
count

8

In [10]:
# strings

In [11]:
'single '

'single '

In [15]:
"this is string"

'this is string'

In [16]:
name = Himanshu
num = 1999
'My name is {} and number is {}'.format(name, num)

NameError: name 'Himanshu' is not defined

In [21]:
name = 'Himanshu'
num = 1999
print('My name is {} and number is {}'.format(name, num))

My name is Himanshu and number is 1999


In [22]:
nest = [1,2,3,[1,4,["Himasnhu"]]]
nest[3][2][4]

IndexError: list index out of range

In [23]:
nest = [1,2,3,[1,4,['Himasnhu']]]
nest[3][2][4]

IndexError: list index out of range

In [24]:
nest[3][1][2]

TypeError: 'int' object is not subscriptable

In [25]:
nest[3][1][0]

TypeError: 'int' object is not subscriptable

In [27]:
print(nest[3][2][0])

Himasnhu


In [36]:
d = {'key':15611616}
d['key']

15611616

In [44]:
s = {1,3,4,56,88,99,56}
s.add(99)

In [45]:
s

{1, 3, 4, 56, 88, 99}

In [39]:
1 == 1.0

True

In [1]:
1==5

False

In [2]:
arr = np.arrange(0,11)

NameError: name 'np' is not defined

In [3]:
import numpy as np

In [ ]:
arr 

In [5]:
arr = np.arange(0,11)

In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
arr_2d = np.array([[2,4,6],[8,6,4],[3,6,9]])

In [24]:
arr_2d

array([[2, 4, 6],
       [8, 6, 4],
       [3, 6, 9]])

In [25]:
arr_2d[1:]

array([[8, 6, 4],
       [3, 6, 9]])

In [26]:
arr_2d[1:,1:]

array([[6, 4],
       [6, 9]])

In [29]:
arr[0:11] = 1

In [30]:
arr

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [38]:
arri = np.arange(0,11)

In [53]:
arri

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
arri*arri

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [61]:
np.exp(arri)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [64]:
array = np.arange(0,10)

In [67]:
array[0:10] = 1

In [71]:
array

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [72]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [78]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [102]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [89]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [98]:
np.random.rand(25)

array([0.98802649, 0.75553498, 0.11879376, 0.00445257, 0.77233948,
       0.95701051, 0.56367719, 0.42525021, 0.34173673, 0.97919687,
       0.21169151, 0.37803586, 0.05471802, 0.91179268, 0.15112764,
       0.40713674, 0.14794046, 0.16182214, 0.32809677, 0.86834664,
       0.97116535, 0.10292694, 0.34194121, 0.95302197, 0.6524376 ])

In [103]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [104]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [105]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [106]:
mat[3,4]

20

In [108]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [110]:
mat[4:]

array([[21, 22, 23, 24, 25]])

In [112]:
mat.sum()

325

In [113]:
np.std(mat)

7.211102550927978

In [117]:
mat.sum(axis = 0)

array([55, 60, 65, 70, 75])

In [1]:
import panda as pd


ModuleNotFoundError: No module named 'panda'

In [5]:
import pandas as pd

In [39]:
labels = ['a','b','c']
my_data = [10,20,30]
arr = np.array(my_data)


In [40]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [41]:
d

{'a': 10, 'b': 20, 'c': 30}

In [45]:
ser1 = pd.Series([1,2,3,4],['Dhanbad','India','Rajkot','wasseypur'])

In [46]:
ser1

Dhanbad      1
India        2
Rajkot       3
wasseypur    4
dtype: int64

DATA FRAMES


In [47]:
from numpy.random import randn

In [48]:
np.random.seed(101)

In [50]:
df = pd.DataFrame(randn(5,4),['A','B','C','D','E'],['X','Y','W','Z']) 

In [52]:
df

X         Y         W         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [53]:
df[W]

NameError: name 'W' is not defined

In [54]:
df.W

A    0.907969
B   -0.848077
C    0.528813
D   -0.933237
E    2.605967
Name: W, dtype: float64

In [57]:
df['X']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: X, dtype: float64

In [58]:
df['new'] = df['X'] + df['Y']

In [59]:
df

X         Y         W         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.334983
B  0.651118 -0.319318 -0.848077  0.605965  0.331800
C -2.018168  0.740122  0.528813 -0.589001 -1.278046
D  0.188695 -0.758872 -0.933237  0.955057 -0.570177
E  0.190794  1.978757  2.605967  0.683509  2.169552

In [65]:
df.drop('new', axis = 1)

X         Y         W         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [66]:
df>0

X      Y      W      Z    new
A   True   True   True   True   True
B   True  False  False   True   True
C  False   True   True  False  False
D   True  False  False   True  False
E   True   True   True   True   True

In [73]:
booldf = df>0

In [74]:
df[booldf]

X         Y         W         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.334983
B  0.651118       NaN       NaN  0.605965  0.331800
C       NaN  0.740122  0.528813       NaN       NaN
D  0.188695       NaN       NaN  0.955057       NaN
E  0.190794  1.978757  2.605967  0.683509  2.169552

In [75]:
df['W']>0

A     True
B    False
C     True
D    False
E     True
Name: W, dtype: bool

In [77]:
 df.reset_index()

index         X         Y         W         Z       new
0     A  2.706850  0.628133  0.907969  0.503826  3.334983
1     B  0.651118 -0.319318 -0.848077  0.605965  0.331800
2     C -2.018168  0.740122  0.528813 -0.589001 -1.278046
3     D  0.188695 -0.758872 -0.933237  0.955057 -0.570177
4     E  0.190794  1.978757  2.605967  0.683509  2.169552

In [79]:
newind = 'CA YN WY OT YU'.split()

In [80]:
newind

['CA', 'YN', 'WY', 'OT', 'YU']

In [82]:
df['states'] = newind


In [83]:
df

X         Y         W         Z       new states
A  2.706850  0.628133  0.907969  0.503826  3.334983     CA
B  0.651118 -0.319318 -0.848077  0.605965  0.331800     YN
C -2.018168  0.740122  0.528813 -0.589001 -1.278046     WY
D  0.188695 -0.758872 -0.933237  0.955057 -0.570177     OT
E  0.190794  1.978757  2.605967  0.683509  2.169552     YU

In [85]:
df.set_index('states')

X         Y         W         Z       new
states                                                  
CA      2.706850  0.628133  0.907969  0.503826  3.334983
YN      0.651118 -0.319318 -0.848077  0.605965  0.331800
WY     -2.018168  0.740122  0.528813 -0.589001 -1.278046
OT      0.188695 -0.758872 -0.933237  0.955057 -0.570177
YU      0.190794  1.978757  2.605967  0.683509  2.169552

In [96]:
left = pd.DataFrame({'key':['K0','K1','K2','K3'],
                     'A':['A0','A1','A2','A3'],
                     'B':['B0','B1','B2','B3']})

right = pd.DataFrame({'key':['K0','K1','K2','K3'],
                     'D':['D0','D1','D2','D3'],
                     'E':['E0','E1','E2','E3']})


In [97]:
left

key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3

In [98]:
right

key   D   E
0  K0  D0  E0
1  K1  D1  E1
2  K2  D2  E2
3  K3  D3  E3

In [99]:
pd.concat([left,right],axis =1)

key   A   B key   D   E
0  K0  A0  B0  K0  D0  E0
1  K1  A1  B1  K1  D1  E1
2  K2  A2  B2  K2  D2  E2
3  K3  A3  B3  K3  D3  E3

In [119]:
pd.merge(left,right,how = 'left',on = 'key')

key   A   B   D   E
0  K0  A0  B0  D0  E0
1  K1  A1  B1  D1  E1
2  K2  A2  B2  D2  E2
3  K3  A3  B3  D3  E3

In [112]:
left1 = pd.DataFrame({'A':['A0','A1','A2','A3'],
                     'B':['B0','B1','B2','B3']},
                 index=['K0','K1','K2','K3'])
                     

right1 = pd.DataFrame({'D':['D0','D1','D2','D3'],
                     'E':['E0','E1','E2','E3']},
                    index=['K0','K1','K2','K3'])
                     


In [113]:
left1.join(right1)

A   B   D   E
K0  A0  B0  D0  E0
K1  A1  B1  D1  E1
K2  A2  B2  D2  E2
K3  A3  B3  D3  E3

In [120]:
 pwd

'C:\\Users\\Himanshu'

In [121]:
data = pd.read_html('https://www.fdic.gov/bank/individual/failed/banklist.html')

In [123]:
data[0].head()

Bank Name     City  ST   CERT  \
0     City National Bank of New Jersey   Newark  NJ  21111   
1                        Resolute Bank   Maumee  OH  58317   
2                Louisa Community Bank   Louisa  KY  58112   
3                 The Enloe State Bank   Cooper  TX  10716   
4  Washington Federal Bank for Savings  Chicago  IL  30570   

               Acquiring Institution       Closing Date       Updated Date  
0                    Industrial Bank   November 1, 2019   November 7, 2019  
1                 Buckeye State Bank   October 25, 2019  November 12, 2019  
2  Kentucky Farmers Bank Corporation   October 25, 2019   November 7, 2019  
3                 Legend Bank, N. A.       May 31, 2019    August 22, 2019  
4                 Royal Savings Bank  December 15, 2017      July 24, 2019

In [124]:
from sqlalchemy import create_engine

In [125]:
engine = create_engine('sqlite:///:memory:')

In [127]:
df.to_sql('my_table',engine)

In [129]:
sqldf = pd.read_sql('my_table',con = engine)

In [130]:
sqldf

index         X         Y         W         Z       new states
0     A  2.706850  0.628133  0.907969  0.503826  3.334983     CA
1     B  0.651118 -0.319318 -0.848077  0.605965  0.331800     YN
2     C -2.018168  0.740122  0.528813 -0.589001 -1.278046     WY
3     D  0.188695 -0.758872 -0.933237  0.955057 -0.570177     OT
4     E  0.190794  1.978757  2.605967  0.683509  2.169552     YU

In [134]:
df.head(3)

X         Y         W         Z       new states
A  2.706850  0.628133  0.907969  0.503826  3.334983     CA
B  0.651118 -0.319318 -0.848077  0.605965  0.331800     YN
C -2.018168  0.740122  0.528813 -0.589001 -1.278046     WY

In [135]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, A to E
Data columns (total 6 columns):
X         5 non-null float64
Y         5 non-null float64
W         5 non-null float64
Z         5 non-null float64
new       5 non-null float64
states    5 non-null object
dtypes: float64(5), object(1)
memory usage: 440.0+ bytes


In [138]:
df['X'].mean()

0.34385783502535094

In [151]:
 df[ df['X']==df['X'].max()]

X         Y         W         Z       new states        x
A  2.70685  0.628133  0.907969  0.503826  3.334983     CA  2.70685

In [141]:
df[df['states'] == 'YN']['new']

B    0.3318
Name: new, dtype: float64